set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10.0)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WINDOWS_TRIPLE)

if(NOT DEFINED WINDOWS_TRIPLE)
    message(FATAL_ERROR "WINDOWS_TRIPLE must select an llvm-mingw target")
endif()

set(LLVM_MINGW_ROOT "/opt/llvm-mingw" CACHE PATH "llvm-mingw root")
set(LLVM_MINGW_BIN "${LLVM_MINGW_ROOT}/bin")
set(CMAKE_C_COMPILER "${LLVM_MINGW_BIN}/${WINDOWS_TRIPLE}-clang")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_BIN}/${WINDOWS_TRIPLE}-clang++")
set(CMAKE_RC_COMPILER "${LLVM_MINGW_BIN}/${WINDOWS_TRIPLE}-windres")
set(CMAKE_AR "${LLVM_MINGW_BIN}/llvm-ar")
set(CMAKE_RANLIB "${LLVM_MINGW_BIN}/llvm-ranlib")
set(CMAKE_STRIP "${LLVM_MINGW_BIN}/llvm-strip")

set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_ROOT}/${WINDOWS_TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
